name: Schedule run phpunit test suite

on:
  schedule:
    - cron: '0 * * * *'
  branchs:

jobs:
  phpunit-test-suite:
    uses: juzaweb/actions/.github/workflows/plugin-test.yml@main
    with:
      vendor: juzaweb
      plugin: ecommerce