name: Schedule run phpunit test suite

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  phpunit-test-suite:
    env:
      LOG_CHANNEL: slack
      LOG_SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Testing
        uses: juzaweb/actions/.github/workflows/plugin-test.yml@main
        with:
          vendor: juzaweb
          plugin: ecommerce
